CREATE DATABASE DB2;

use DB2;


SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE Users(idUser INT NOT NULL AUTO_INCREMENT,id1 VARCHAR(10) NOT NULL, PRIMARY KEY(idUser));

SET FOREIGN_KEY_CHECKS = 1;

GRANT ALL ON DB2.* TO root IDENTIFIED BY '1234';

INSERT INTO Users(id1) VALUES('Abraham1');
INSERT INTO Users(id1) VALUES('Abraham2');
INSERT INTO Users(id1) VALUES('Abraham3');
