package entity;
// Generated 13/11/2017 12:35:53 AM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String id;
     private String password;
     private Integer tipo;

    public Users() {
    }

	
    public Users(String id, String password) {
        this.id = id;
        this.password = password;
    }
    public Users(String id, String password, Integer tipo) {
       this.id = id;
       this.password = password;
       this.tipo = tipo;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }




}


